package Podologia;


import podol.conexao.PodolConexao;




 
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlfoto = new javax.swing.JLabel();
        jlnome = new javax.swing.JLabel();
        jllogin = new javax.swing.JLabel();
        jlusuario = new javax.swing.JLabel();
        jlsenha = new javax.swing.JLabel();
        btacessar = new javax.swing.JButton();
        btcancelar = new javax.swing.JButton();
        btlimpar = new javax.swing.JButton();
        tfusuario = new javax.swing.JTextField();
        psdsenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela de Acesso");
        setBackground(new java.awt.Color(0, 153, 255));
        setResizable(false);

        jlfoto.setIcon(new javax.swing.ImageIcon("C:\\Users\\brlima\\Documents\\PROJETOS JAVA\\Podologia\\IMG_20150306_200007904.jpg")); // NOI18N

        jlnome.setFont(new java.awt.Font("Garamond", 1, 48)); // NOI18N
        jlnome.setText("Clínica de Podologia Simone Lima");

        jllogin.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jllogin.setText("Tela de Login");

        jlusuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlusuario.setText("Usuário (user):");

        jlsenha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlsenha.setText("Senha (password):");

        btacessar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btacessar.setIcon(new javax.swing.ImageIcon("C:\\Users\\brlima\\Documents\\PROJETOS JAVA\\Podologia\\Unlock.png")); // NOI18N
        btacessar.setText("Acessar");
        btacessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btacessarActionPerformed(evt);
            }
        });

        btcancelar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btcancelar.setIcon(new javax.swing.ImageIcon("C:\\Users\\brlima\\Documents\\PROJETOS JAVA\\Podologia\\No.png")); // NOI18N
        btcancelar.setText("Cancelar");
        btcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcancelarActionPerformed(evt);
            }
        });

        btlimpar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btlimpar.setIcon(new javax.swing.ImageIcon("C:\\Users\\brlima\\Documents\\PROJETOS JAVA\\Podologia\\Problem.png")); // NOI18N
        btlimpar.setText("Limpar");

        tfusuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfusuario.setForeground(new java.awt.Color(0, 204, 204));
        tfusuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tfusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfusuarioActionPerformed(evt);
            }
        });

        psdsenha.setForeground(new java.awt.Color(255, 0, 51));
        psdsenha.setText("jPasswordField1");
        psdsenha.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        psdsenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psdsenhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jlnome))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jlfoto)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(187, 187, 187)
                                .addComponent(jllogin))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(btacessar)
                                .addGap(21, 21, 21)
                                .addComponent(btlimpar)
                                .addGap(18, 18, 18)
                                .addComponent(btcancelar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addComponent(tfusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(125, 125, 125)
                                .addComponent(psdsenha, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlusuario)
                                    .addComponent(jlsenha))))))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btacessar, btcancelar, btlimpar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jlnome, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jllogin)
                        .addGap(42, 42, 42)
                        .addComponent(jlusuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jlsenha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(psdsenha))
                    .addComponent(jlfoto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btacessar)
                    .addComponent(btlimpar)
                    .addComponent(btcancelar))
                .addGap(43, 43, 43))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btacessar, btcancelar, btlimpar});

        setSize(new java.awt.Dimension(800, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfusuarioActionPerformed

    private void psdsenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psdsenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_psdsenhaActionPerformed
    private void btacessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btacessarActionPerformed
       
        PodolConexao pc = new PodolConexao();
        pc.PodolConexao(tfusuario.getText(), psdsenha.getText());
        if (pc.acesso == true);   
        TelaPrincipal tp = new TelaPrincipal();
        tp.show();
        tp.setExtendedState(TelaPrincipal.MAXIMIZED_BOTH);
        dispose();
       
        if (pc.acesso == false){
    tfusuario.setText("");
    psdsenha.setText("");
    tfusuario.requestFocus();
    pc.acesso=false;
}
               
        
        
    }//GEN-LAST:event_btacessarActionPerformed

    
    private void btcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcancelarActionPerformed
       System.exit(0);
    }//GEN-LAST:event_btcancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            TelaLogin tela = new TelaLogin();
            tela.setLocationRelativeTo(null);
            tela.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btacessar;
    private javax.swing.JButton btcancelar;
    private javax.swing.JButton btlimpar;
    private javax.swing.JLabel jlfoto;
    private javax.swing.JLabel jllogin;
    private javax.swing.JLabel jlnome;
    private javax.swing.JLabel jlsenha;
    private javax.swing.JLabel jlusuario;
    private javax.swing.JPasswordField psdsenha;
    private javax.swing.JTextField tfusuario;
    // End of variables declaration//GEN-END:variables
}
